// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

const customers = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    name: 'Hector Simpson',
    email: 'hector@simpson.com',
    image_url: '/customers/hector-simpson.png',
  },
  {
    id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    name: 'Steven Tey',
    email: 'steven@tey.com',
    image_url: '/customers/steven-tey.png',
  },
  {
    id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    name: 'Steph Dietz',
    email: 'steph@dietz.com',
    image_url: '/customers/steph-dietz.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    name: 'Emil Kowalski',
    email: 'emil@kowalski.com',
    image_url: '/customers/emil-kowalski.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const invoices = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: 'pending',
    date: '2022-12-06',
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: 'pending',
    date: '2022-11-14',
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: 'paid',
    date: '2022-10-29',
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: 'paid',
    date: '2023-09-10',
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: 'pending',
    date: '2023-08-05',
  },
  {
    customer_id: customers[7].id,
    amount: 54246,
    status: 'pending',
    date: '2023-07-16',
  },
  {
    customer_id: customers[6].id,
    amount: 666,
    status: 'pending',
    date: '2023-06-27',
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: 'paid',
    date: '2023-06-09',
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: 'paid',
    date: '2023-06-17',
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: 'paid',
    date: '2023-06-07',
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: 'paid',
    date: '2023-08-19',
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-03',
  },
  {
    customer_id: customers[2].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-18',
  },
  {
    customer_id: customers[0].id,
    amount: 8945,
    status: 'paid',
    date: '2023-10-04',
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: 'paid',
    date: '2022-06-05',
  },
];

const revenue = [
  { month: 'Jan', revenue: 2000 },
  { month: 'Feb', revenue: 1800 },
  { month: 'Mar', revenue: 2200 },
  { month: 'Apr', revenue: 2500 },
  { month: 'May', revenue: 2300 },
  { month: 'Jun', revenue: 3200 },
  { month: 'Jul', revenue: 3500 },
  { month: 'Aug', revenue: 3700 },
  { month: 'Sep', revenue: 2500 },
  { month: 'Oct', revenue: 2800 },
  { month: 'Nov', revenue: 3000 },
  { month: 'Dec', revenue: 4800 },
];
const movies = [
  {
    adult: false,
    backdrop_path: '/sR0SpCrXamlIkYMdfz83sFn5JS6.jpg',
    genre_ids: [28, 878, 12, 14],
    id: 823464,
    original_language: 'en',
    original_title: 'Godzilla x Kong: The New Empire',
    overview:
      'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    popularity: 3911.344,
    poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    release_date: '2024-03-27',
    title: 'Godzilla x Kong: The New Empire',
    video: false,
    vote_average: 6.727,
    vote_count: 475,
  },
  {
    adult: false,
    backdrop_path: '/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg',
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: 'en',
    original_title: 'Kung Fu Panda 4',
    overview:
      'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
    popularity: 2781.667,
    poster_path: '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    release_date: '2024-03-02',
    title: 'Kung Fu Panda 4',
    video: false,
    vote_average: 6.7,
    vote_count: 628,
  },
  {
    adult: false,
    backdrop_path: '/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg',
    genre_ids: [28, 53],
    id: 359410,
    original_language: 'en',
    original_title: 'Road House',
    overview:
      'Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.',
    popularity: 2160.52,
    poster_path: '/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg',
    release_date: '2024-03-08',
    title: 'Road House',
    video: false,
    vote_average: 7.101,
    vote_count: 1280,
  },
  {
    adult: false,
    backdrop_path: '/9c0lHTXRqDBxeOToVzRu0GArSne.jpg',
    genre_ids: [878, 28],
    id: 935271,
    original_language: 'en',
    original_title: 'After the Pandemic',
    overview:
      "Set in a post-apocalyptic world where a global airborne pandemic has wiped out 90% of the Earth's population and only the young and immune have endured as scavengers. For Ellie and Quinn, the daily challenges to stay alive are compounded when they become hunted by the merciless Stalkers.",
    popularity: 1727.4,
    poster_path: '/p1LbrdJ53dGfEhRopG71akfzOVu.jpg',
    release_date: '2022-03-01',
    title: 'After the Pandemic',
    video: false,
    vote_average: 5.294,
    vote_count: 17,
  },
  {
    adult: false,
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    genre_ids: [878, 12],
    id: 693134,
    original_language: 'en',
    original_title: 'Dune: Part Two',
    overview:
      'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
    popularity: 1380.968,
    poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    release_date: '2024-02-27',
    title: 'Dune: Part Two',
    video: false,
    vote_average: 8.358,
    vote_count: 2519,
  },
  {
    adult: false,
    backdrop_path: '/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg',
    genre_ids: [28, 14],
    id: 634492,
    original_language: 'en',
    original_title: 'Madame Web',
    overview:
      'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.',
    popularity: 1501.664,
    poster_path: '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg',
    release_date: '2024-02-14',
    title: 'Madame Web',
    video: false,
    vote_average: 5.673,
    vote_count: 995,
  },
  {
    adult: false,
    backdrop_path: '/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg',
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: 'en',
    original_title: 'Migration',
    overview:
      'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
    popularity: 1234.623,
    poster_path: '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
    release_date: '2023-12-06',
    title: 'Migration',
    video: false,
    vote_average: 7.535,
    vote_count: 1106,
  },
  {
    adult: false,
    backdrop_path: '/2C3CdVzINUm5Cm1lrbT2uiRstwX.jpg',
    genre_ids: [28, 14, 10752],
    id: 856289,
    original_language: 'zh',
    original_title: '封神第一部：朝歌风云',
    overview:
      'Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.',
    popularity: 1028.294,
    poster_path: '/ccJpK0rqzhQeP7Mrs2uKqObFY4L.jpg',
    release_date: '2023-07-20',
    title: 'Creation of the Gods I: Kingdom of Storms',
    video: false,
    vote_average: 6.846,
    vote_count: 178,
  },
  {
    adult: false,
    backdrop_path: '/deLWkOLZmBNkm8p16igfapQyqeq.jpg',
    genre_ids: [14, 28, 12],
    id: 763215,
    original_language: 'en',
    original_title: 'Damsel',
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 1003.315,
    poster_path: '/AgHbB9DCE9aE57zkHjSmseszh6e.jpg',
    release_date: '2024-03-07',
    title: 'Damsel',
    video: false,
    vote_average: 7.133,
    vote_count: 1483,
  },
  {
    adult: false,
    backdrop_path: '/TGsfNWkASegCfAn6ED1b08a9O6.jpg',
    genre_ids: [27, 9648, 53],
    id: 1125311,
    original_language: 'en',
    original_title: 'Imaginary',
    overview:
      'When Jessica moves back into her childhood home with her family, her youngest stepdaughter Alice develops an eerie attachment to a stuffed bear named Chauncey she finds in the basement. Alice starts playing games with Chauncey that begin playful and become increasingly sinister. As Alice’s behavior becomes more and more concerning, Jessica intervenes only to realize Chauncey is much more than the stuffed toy bear she believed him to be.',
    popularity: 894.111,
    poster_path: '/9u6HEtZJdZDjPGGJq6YEuhPnoan.jpg',
    release_date: '2024-03-06',
    title: 'Imaginary',
    video: false,
    vote_average: 6.0,
    vote_count: 161,
  },
  {
    adult: false,
    backdrop_path: '/rKmp0vm6PNaFA0g1bzM70eyWJ6I.jpg',
    genre_ids: [28],
    id: 873972,
    original_language: 'en',
    original_title: 'Hunters',
    overview:
      'As John T. Wrecker continues his task of protecting a group of refugees from a virus, the threat of something new and even more dangerous grows ever closer in the form of monstrous mutants.',
    popularity: 1068.293,
    poster_path: '/3UKlVa1CBeQkRksHV5OfFTO52qd.jpg',
    release_date: '2021-09-13',
    title: 'Hunters',
    video: false,
    vote_average: 5.3,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: '/wUp0bUXaveR40ikBhDgWwNTijuD.jpg',
    genre_ids: [28, 9648, 53],
    id: 1181548,
    original_language: 'en',
    original_title: 'Heart of the Hunter',
    overview:
      'A retired assassin is pulled back into action when his friend uncovers a dangerous conspiracy at the heart of the South African government.',
    popularity: 1154.73,
    poster_path: '/n726fdyL1dGwt15bY7Nj3XOXc4Q.jpg',
    release_date: '2024-03-28',
    title: 'Heart of the Hunter',
    video: false,
    vote_average: 5.984,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: '/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg',
    genre_ids: [878, 28, 14, 12],
    id: 601796,
    original_language: 'ko',
    original_title: '외계+인 1부',
    overview:
      "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.",
    popularity: 877.798,
    poster_path: '/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg',
    release_date: '2022-07-20',
    title: 'Alienoid',
    video: false,
    vote_average: 7.074,
    vote_count: 249,
  },
  {
    adult: false,
    backdrop_path: '/mIBG74mhGEJnBubhYLkCtvplcNr.jpg',
    genre_ids: [27],
    id: 437342,
    original_language: 'en',
    original_title: 'The First Omen',
    overview:
      'When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.',
    popularity: 745.812,
    poster_path: '/jT6awzVlAf0ZOoXbWhIXu1y5sDu.jpg',
    release_date: '2024-04-03',
    title: 'The First Omen',
    video: false,
    vote_average: 6.8,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: '/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg',
    genre_ids: [28, 53],
    id: 984324,
    original_language: 'fr',
    original_title: 'Le salaire de la peur',
    overview:
      'When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.',
    popularity: 1040.298,
    poster_path: '/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg',
    release_date: '2024-03-28',
    title: 'The Wages of Fear',
    video: false,
    vote_average: 5.868,
    vote_count: 110,
  },
  {
    adult: false,
    backdrop_path: '/4woSOUD0equAYzvwhWBHIJDCM88.jpg',
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: 'en',
    original_title: 'No Way Up',
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 880.551,
    poster_path: '/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg',
    release_date: '2024-01-18',
    title: 'No Way Up',
    video: false,
    vote_average: 6.317,
    vote_count: 340,
  },
  {
    adult: false,
    backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
    genre_ids: [28, 878, 53],
    id: 399566,
    original_language: 'en',
    original_title: 'Godzilla vs. Kong',
    overview:
      'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    popularity: 682.766,
    poster_path: '/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
    release_date: '2021-03-24',
    title: 'Godzilla vs. Kong',
    video: false,
    vote_average: 7.624,
    vote_count: 9548,
  },
  {
    adult: false,
    backdrop_path: '/oFAukXiMPrwLpbulGmB5suEZlrm.jpg',
    genre_ids: [28, 12, 878, 14, 18],
    id: 624091,
    original_language: 'id',
    original_title: 'Sri Asih',
    overview:
      'Alana discover the truth about her origin: she’s not an ordinary human being. She may be the gift for humanity and become its protector as Sri Asih. Or a destruction, if she can’t control her anger.',
    popularity: 661.412,
    poster_path: '/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg',
    release_date: '2022-11-17',
    title: 'Sri Asih',
    video: false,
    vote_average: 6.226,
    vote_count: 73,
  },
  {
    adult: false,
    backdrop_path: '/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg',
    genre_ids: [878, 27, 28],
    id: 940721,
    original_language: 'ja',
    original_title: 'ゴジラ-1.0',
    overview:
      'Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.',
    popularity: 664.385,
    poster_path: '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
    release_date: '2023-11-03',
    title: 'Godzilla Minus One',
    video: false,
    vote_average: 7.9,
    vote_count: 470,
  },
  {
    adult: false,
    backdrop_path: '/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg',
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: 'en',
    original_title: 'Land of Bad',
    overview:
      'When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.',
    popularity: 612.405,
    poster_path: '/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg',
    release_date: '2024-01-25',
    title: 'Land of Bad',
    video: false,
    vote_average: 7.106,
    vote_count: 489,
  },
  {
    adult: false,
    backdrop_path: '/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg',
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: 'en',
    original_title: 'Land of Bad',
    overview:
      'When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.',
    popularity: 612.405,
    poster_path: '/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg',
    release_date: '2024-01-25',
    title: 'Land of Bad',
    video: false,
    vote_average: 7.106,
    vote_count: 489,
  },
  {
    adult: false,
    backdrop_path: '/qSc5JzPvSm6KxVv54nrn7SNXFtk.jpg',
    genre_ids: [16, 10402, 35],
    id: 1192209,
    original_language: 'pt',
    original_title: 'Arca de Noé',
    overview:
      "A pair of mice attempt to board Noah's Ark: Vini, a charismatic poet with terrible stage fright, and Tito, a talented and charming guitarist. When the rains come, only one male and one female of each species is allowed on Noah's Ark. With the help of an ingenious cockroach and fate's good luck, Vini and Tito sneak their way onto the Ark and together avert a showdown among the ships carnivores and plant eaters. All the while, the animals perform a series of classic songs inspired by world renowned poet, Vinicius de Moraes. Can these talented stowaways use music to break the tension and help these cooped up creatures survive the 40 days and 40 nights together?",
    popularity: 561.993,
    poster_path: '/j1Rjw6a62UwrbTNT0I3JzZnnCmr.jpg',
    release_date: '2024-01-05',
    title: "Noah's Ark",
    video: false,
    vote_average: 6.917,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: '/3Kzc6V4MWs3RXCmE5DhAYnfWL8F.jpg',
    genre_ids: [16, 35, 878],
    id: 1239251,
    original_language: 'en',
    original_title: 'Megamind vs. the Doom Syndicate',
    overview:
      "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
    popularity: 543.751,
    poster_path: '/fko8CPrnspewLXgFUlUkivyvpHX.jpg',
    release_date: '2024-03-29',
    title: 'Megamind vs. the Doom Syndicate',
    video: false,
    vote_average: 5.667,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
    genre_ids: [16, 10751, 14, 12],
    id: 1022796,
    original_language: 'en',
    original_title: 'Wish',
    overview:
      'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.',
    popularity: 510.219,
    poster_path: '/vgJZSqKMXWDDx09iSIStGKfHMku.jpg',
    release_date: '2023-11-13',
    title: 'Wish',
    video: false,
    vote_average: 6.57,
    vote_count: 989,
  },
  {
    adult: false,
    backdrop_path: '/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg',
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: 'en',
    original_title: 'Poor Things',
    overview:
      'Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.',
    popularity: 464.417,
    poster_path: '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
    release_date: '2023-12-07',
    title: 'Poor Things',
    video: false,
    vote_average: 7.809,
    vote_count: 2989,
  },
  {
    adult: false,
    backdrop_path: '/8ohejkcQkNgkJgLn71Ws6Kd35g0.jpg',
    genre_ids: [18, 36],
    id: 872585,
    original_language: 'en',
    original_title: 'Oppenheimer',
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 521.118,
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    release_date: '2023-07-19',
    title: 'Oppenheimer',
    video: false,
    vote_average: 8.112,
    vote_count: 7561,
  },
  {
    adult: false,
    backdrop_path: '/yyFc8Iclt2jxPmLztbP617xXllT.jpg',
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: 'en',
    original_title: 'Wonka',
    overview:
      'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
    popularity: 510.857,
    poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
    release_date: '2023-12-06',
    title: 'Wonka',
    video: false,
    vote_average: 7.202,
    vote_count: 2783,
  },
  {
    adult: false,
    backdrop_path: '/4Ep2KivIBUZbkS7kHjW7Qywnhhj.jpg',
    genre_ids: [28],
    id: 1049948,
    original_language: 'en',
    original_title: 'Vikings: Battle of Heirs',
    overview:
      "A young Viking must come to terms with the realization that he may be the King's son, who was switched at birth, but not before others try to take his rightful place.",
    popularity: 590.6,
    poster_path: '/87goLbbqrJqAxqDS5cBsik1zKT.jpg',
    release_date: '2023-04-28',
    title: 'Vikings: Battle of Heirs',
    video: false,
    vote_average: 6.5,
    vote_count: 24,
  },
  {
    adult: false,
    backdrop_path: '/mEoIDEiePnYj178H9znzbl9zvky.jpg',
    genre_ids: [28],
    id: 1006540,
    original_language: 'en',
    original_title: 'Bullet Train Down',
    overview:
      "On its maiden run, the world's fastest bullet train is rigged with a bomb that will explode if it dips below 200 mph.",
    popularity: 499.511,
    poster_path: '/5a7cocgyVuFjYV71neDIGVzD6Yq.jpg',
    release_date: '2022-08-01',
    title: 'Bullet Train Down',
    video: false,
    vote_average: 5.36,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: '/u0P5drNyTrZoGyJONPcZGbv1mNP.jpg',
    genre_ids: [28, 53],
    id: 1124127,
    original_language: 'en',
    original_title: 'Air Force One Down',
    overview:
      "On her first assignment aboard Air Force One, a rookie Secret Service agent faces the ultimate test when terrorists hijack the plane, intent on derailing a pivotal energy deal. With the President's life on the line and a global crisis at stake, her bravery and skills are pushed to the limit in a relentless battle that could change the course of history.",
    popularity: 472.996,
    poster_path: '/nKPoSD4pZ3s3CJ9g3cqWRcQ41TC.jpg',
    release_date: '2024-02-09',
    title: 'Air Force One Down',
    video: false,
    vote_average: 6.439,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: '/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg',
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: 'en',
    original_title: 'Argylle',
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 550.322,
    poster_path: '/siduVKgOnABO4WH4lOwPQwaGwJp.jpg',
    release_date: '2024-01-31',
    title: 'Argylle',
    video: false,
    vote_average: 6.154,
    vote_count: 804,
  },
  {
    adult: false,
    backdrop_path: '/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg',
    genre_ids: [878, 28, 80],
    id: 932420,
    original_language: 'en',
    original_title: 'Code 8 Part II',
    overview:
      'In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.',
    popularity: 500.644,
    poster_path: '/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg',
    release_date: '2024-02-27',
    title: 'Code 8 Part II',
    video: false,
    vote_average: 6.511,
    vote_count: 400,
  },
  {
    adult: false,
    backdrop_path: '/9RIp2idEKHRAnB2MqqfatIuBkko.jpg',
    genre_ids: [35],
    id: 1074049,
    original_language: 'es',
    original_title: 'Ocho Apellidos Marroquís',
    overview:
      "Follows the Díaz-Aguirre family, whose perfect universe turns upside down after the death of the patriarch, who in his will asks his wife to recover the 'Sardinete', his first fishing boat which is rusting in a Moroccan port.",
    popularity: 415.25,
    poster_path: '/hRVxoyKLAGKlvjfVy2dI76rKfX9.jpg',
    release_date: '2023-12-01',
    title: 'A Moroccan Affair',
    video: false,
    vote_average: 5.909,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
    genre_ids: [10749, 35],
    id: 1072790,
    original_language: 'en',
    original_title: 'Anyone But You',
    overview:
      'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
    popularity: 455.427,
    poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
    release_date: '2023-12-21',
    title: 'Anyone But You',
    video: false,
    vote_average: 7.069,
    vote_count: 1267,
  },
  {
    adult: false,
    backdrop_path: '/uovH5k4BAEPqXqxgwVrTtqH169g.jpg',
    genre_ids: [878, 28],
    id: 373571,
    original_language: 'en',
    original_title: 'Godzilla: King of the Monsters',
    overview:
      "Follows the heroic efforts of the crypto-zoological agency Monarch as its members face off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah. When these ancient super-species, thought to be mere myths, rise again, they all vie for supremacy, leaving humanity's very existence hanging in the balance.",
    popularity: 463.561,
    poster_path: '/fQ40gmFM4p03tXwMxQQKh2cCBW4.jpg',
    release_date: '2019-05-29',
    title: 'Godzilla: King of the Monsters',
    video: false,
    vote_average: 6.686,
    vote_count: 5813,
  },
  {
    adult: false,
    backdrop_path: '/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg',
    genre_ids: [14, 12, 35],
    id: 967847,
    original_language: 'en',
    original_title: 'Ghostbusters: Frozen Empire',
    overview:
      "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
    popularity: 363.213,
    poster_path: '/6faYaQyiBPhqAizldJKq21mIVaE.jpg',
    release_date: '2024-03-20',
    title: 'Ghostbusters: Frozen Empire',
    video: false,
    vote_average: 6.7,
    vote_count: 168,
  },
  {
    adult: false,
    backdrop_path: '/hIUs8RzKlrzgbWxn2EpWmiTFqCc.jpg',
    genre_ids: [878, 53],
    id: 870404,
    original_language: 'en',
    original_title: 'Meteor',
    overview:
      'After a meteor collides into Earth, a lonely rancher and a lost young girl are on the run from vicious mercenaries.',
    popularity: 454.767,
    poster_path: '/tVMddOS5bi3YPVPgTPlEw0TOWoF.jpg',
    release_date: '2021-09-01',
    title: 'Meteor',
    video: false,
    vote_average: 5.45,
    vote_count: 90,
  },
  {
    adult: false,
    backdrop_path: '/oFS0DgInCdvYRwaPkl3BLpmIuq5.jpg',
    genre_ids: [28, 80, 18, 9648, 878, 53],
    id: 1013240,
    original_language: 'id',
    original_title: '24 Jam Bersama Gaspar',
    overview:
      'With only 24 hours left to live, a private investigator follows a trail of confounding clues to uncover the disappearance of his childhood friend.',
    popularity: 416.15,
    poster_path: '/8jJKM0ZR3GQo6E3CUkMKKVa4S8B.jpg',
    release_date: '2023-10-06',
    title: '24 Hours with Gaspar',
    video: false,
    vote_average: 6.4,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: '/zCjZfevPFBbOh2SAx2syIBHSqEI.jpg',
    genre_ids: [28, 18, 878],
    id: 124905,
    original_language: 'en',
    original_title: 'Godzilla',
    overview:
      'Ford Brody, a Navy bomb expert, has just reunited with his family in San Francisco when he is forced to go to Japan to help his estranged father, Joe. Soon, both men are swept up in an escalating crisis when an ancient alpha predator arises from the sea to combat malevolent adversaries that threaten the survival of humanity. The creatures leave colossal destruction in their wake, as they make their way toward their final battleground: San Francisco.',
    popularity: 350.397,
    poster_path: '/zokD6uxR2iWfYM3Y84yGJvnNTK7.jpg',
    release_date: '2014-05-14',
    title: 'Godzilla',
    video: false,
    vote_average: 6.319,
    vote_count: 8746,
  },
  {
    adult: false,
    backdrop_path: '/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg',
    genre_ids: [18, 10749],
    id: 1010581,
    original_language: 'es',
    original_title: 'Culpa mía',
    overview:
      "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
    popularity: 333.916,
    poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
    release_date: '2023-06-08',
    title: 'My Fault',
    video: false,
    vote_average: 7.993,
    vote_count: 2414,
  },
  {
    adult: false,
    backdrop_path: '/rNP32TLwnUky6uuUyCIDatGCd6x.jpg',
    genre_ids: [10751, 14, 35],
    id: 1027604,
    original_language: 'cs',
    original_title: 'Princezna zakletá v čase 2',
    overview:
      'It follows young alchemist Amélie as she acquires a magical power: partially influencing the flow of time. But she is split in time, and Amélie from the present meets Améliw from the past, who accompanies her every step of the way.',
    popularity: 464.163,
    poster_path: '/ywzbF5YSBfZ7XqcGO9YR6Gy4VFt.jpg',
    release_date: '2022-11-17',
    title: "Princess Cursed in Time: Alchemist's Quest",
    video: false,
    vote_average: 7.4,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg',
    genre_ids: [28, 80],
    id: 1046090,
    original_language: 'zh',
    original_title: '周處除三害',
    overview:
      'The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.',
    popularity: 404.458,
    poster_path: '/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg',
    release_date: '2023-10-06',
    title: 'The Pig, the Snake and the Pigeon',
    video: false,
    vote_average: 7.353,
    vote_count: 143,
  },
  {
    adult: false,
    backdrop_path: '/udRawm2AYKn8pWvYk8Hil5RByog.jpg',
    genre_ids: [53, 27, 28, 878, 18],
    id: 1223272,
    original_language: 'en',
    original_title: 'Contagion of Fear',
    overview:
      'A catastrophic train derailment sends the city spiraling into chaos. But the derailment is just the beginning. A biological gas attack sees crash survivors collapsing and dying within minutes. And the sickness is rapidly spreading.',
    popularity: 373.966,
    poster_path: '/wjXGhkqHCFIt6XuLoPfmoRrX6Km.jpg',
    release_date: '2024-01-16',
    title: 'Contagion of Fear',
    video: false,
    vote_average: 7.5,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: '/midCh3iVxaG3dUOrP9TnUpNcGm.jpg',
    genre_ids: [16, 12, 14],
    id: 508883,
    original_language: 'ja',
    original_title: '君たちはどう生きるか',
    overview:
      'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy\'s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
    popularity: 319.192,
    poster_path: '/f4oZTcfGrVTXKTWg157AwikXqmP.jpg',
    release_date: '2023-07-14',
    title: 'The Boy and the Heron',
    video: false,
    vote_average: 7.4,
    vote_count: 1155,
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 388.735,
    poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    release_date: '2023-05-17',
    title: 'Fast X',
    video: false,
    vote_average: 7.137,
    vote_count: 5027,
  },
  {
    adult: false,
    backdrop_path: '/8H6YiYWtrIS6jUG8SBhAltkuHVA.jpg',
    genre_ids: [27, 53],
    id: 821669,
    original_language: 'th',
    original_title: 'ภาพหวาด',
    overview:
      "Ruja inherited the painting from her deceased father and hired Tim, an art restorer to repair it, but they don't know that this invaluable art came with invaluable horror.",
    popularity: 314.01,
    poster_path: '/8MTiGWVC3IPHc597w1NU18Vh5Wa.jpg',
    release_date: '2022-02-24',
    title: 'Cracked',
    video: false,
    vote_average: 5.441,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: '/s9YTxwaByYeoSqugYjJJtZjMRAG.jpg',
    genre_ids: [28, 27, 35, 53],
    id: 1211483,
    original_language: 'en',
    original_title: 'Skal - Fight for Survival',
    overview:
      "My name's Arthur, a huge Internet star who's just hit 3 million subs. While in the midst of throwing an epic party to celebrate, the universe had the balls to bring on the effing apocalypse and cut my night short. What was supposed to be a perfect hangover, has turned into an epic fight for survival.",
    popularity: 369.71,
    poster_path: '/1On8iF3AsFIbpyfZg1xiGWMAFBn.jpg',
    release_date: '2023-11-24',
    title: 'Skal - Fight for Survival',
    video: false,
    vote_average: 5.325,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: '/w4pRLYYbhHn3sh9kqRgPZM6GjyS.jpg',
    genre_ids: [878, 12, 28],
    id: 609681,
    original_language: 'en',
    original_title: 'The Marvels',
    overview:
      'Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.',
    popularity: 373.65,
    poster_path: '/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg',
    release_date: '2023-11-08',
    title: 'The Marvels',
    video: false,
    vote_average: 6.201,
    vote_count: 2161,
  },
  {
    adult: false,
    backdrop_path: '/bckxSN9ueOgm0gJpVJmPQrecWul.jpg',
    genre_ids: [28, 12, 14],
    id: 572802,
    original_language: 'en',
    original_title: 'Aquaman and the Lost Kingdom',
    overview:
      "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
    popularity: 339.387,
    poster_path: '/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg',
    release_date: '2023-12-20',
    title: 'Aquaman and the Lost Kingdom',
    video: false,
    vote_average: 6.811,
    vote_count: 2208,
  },
  {
    adult: false,
    backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
    genre_ids: [16, 10751, 12, 14, 35],
    id: 502356,
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    popularity: 283.824,
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    release_date: '2023-04-05',
    title: 'The Super Mario Bros. Movie',
    video: false,
    vote_average: 7.683,
    vote_count: 8268,
  },
  {
    adult: false,
    backdrop_path: '/zCViszfnUOCJBTCTr9YN1VWvqnn.jpg',
    genre_ids: [28, 35],
    id: 897087,
    original_language: 'en',
    original_title: 'Freelance',
    overview:
      'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.',
    popularity: 346.369,
    poster_path: '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg',
    release_date: '2023-10-05',
    title: 'Freelance',
    video: false,
    vote_average: 6.585,
    vote_count: 704,
  },
  {
    adult: false,
    backdrop_path: '/pI5jxew0I9kub4IXrtsOB8F40dw.jpg',
    genre_ids: [16, 10751, 18, 12, 14],
    id: 1022789,
    original_language: 'en',
    original_title: 'Inside Out 2',
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 276.373,
    poster_path: '/xeqXXTE1Cd3qNaAEOT6qbhhCsgJ.jpg',
    release_date: '2024-06-12',
    title: 'Inside Out 2',
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/i7nnmCTnjK50vNqbMfVtmoVULWJ.jpg',
    genre_ids: [28],
    id: 1081620,
    original_language: 'en',
    original_title: 'The Weapon',
    overview:
      'Dallas is a one-man killing machine on a mysterious rampage. His attacks on biker gangs and meth labs anger the Vegas mob boss who’s holding Dallas’ girlfriend hostage. But who is Dallas working for? Even torture won’t make him talk, and he won’t stop until justice is served.',
    popularity: 300.239,
    poster_path: '/slQYCDzCMM8SBh9Xa3aPeM2fekA.jpg',
    release_date: '2023-02-17',
    title: 'The Weapon',
    video: false,
    vote_average: 5.891,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: '/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg',
    genre_ids: [28, 53, 18],
    id: 866398,
    original_language: 'en',
    original_title: 'The Beekeeper',
    overview:
      "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    popularity: 305.066,
    poster_path: '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg',
    release_date: '2024-01-08',
    title: 'The Beekeeper',
    video: false,
    vote_average: 7.476,
    vote_count: 1939,
  },
  {
    adult: false,
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 286.379,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.626,
    vote_count: 11139,
  },
  {
    adult: false,
    backdrop_path: '/lmDBCAFJjXQwU7kDYbdN2pV9sAV.jpg',
    genre_ids: [16, 27],
    id: 366171,
    original_language: 'en',
    original_title: 'To Your Last Death',
    overview:
      'In order to save her siblings, a young woman takes on her father and the powerful entity known as Gamemaster, who ensnares humans into diabolical plots while her species gambles on the outcome.',
    popularity: 286.629,
    poster_path: '/btV7OWc6IbjrwZiB75klmgi3CsY.jpg',
    release_date: '2019-11-30',
    title: 'To Your Last Death',
    video: false,
    vote_average: 5.8,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
    genre_ids: [28, 12, 878],
    id: 667538,
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview:
      'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
    popularity: 275.006,
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    release_date: '2023-06-06',
    title: 'Transformers: Rise of the Beasts',
    video: false,
    vote_average: 7.343,
    vote_count: 4176,
  },
  {
    adult: false,
    backdrop_path: '/lP0G6f00CjOKdRECyGrT0kaMSrL.jpg',
    genre_ids: [18],
    id: 383634,
    original_language: 'ja',
    original_title: '肉体の門',
    overview:
      'Prostitutes in burnt out Tokyo ghetto of post-WWII Japan peddle their flesh and save one-third of their money for a proposed dancehall to be named Paradise. The hookers live in a bombed-out building, but they accept the precarious situation with typical resolve.',
    popularity: 236.428,
    poster_path: '/raNbLci95MJ3L3dMnG7L7bD37lY.jpg',
    release_date: '1988-04-09',
    title: 'Carmen 1945',
    video: false,
    vote_average: 4.0,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: '/ruKNVJFViAyR4jguVboFXTskMOe.jpg',
    genre_ids: [53, 28, 27],
    id: 1028703,
    original_language: 'en',
    original_title: 'The OctoGames',
    overview:
      'Eight contestants compete in eight deadly, classic children\'s games. They seek fame beyond their wildest dreams, competing for the chance to take over the YouTube channel of the famous yet elusive masked content creator known only as "JaxPro".',
    popularity: 349.391,
    poster_path: '/qGz5rffXhegQH5PGUDiObqoOt06.jpg',
    release_date: '2022-10-07',
    title: 'The OctoGames',
    video: false,
    vote_average: 5.597,
    vote_count: 103,
  },
  {
    adult: false,
    backdrop_path: '/pA4sNvcohTNPx3AhEEeIu8gSt7h.jpg',
    genre_ids: [16, 35, 10751, 14, 10749, 12],
    id: 976573,
    original_language: 'en',
    original_title: 'Elemental',
    overview:
      'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
    popularity: 264.051,
    poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
    release_date: '2023-06-14',
    title: 'Elemental',
    video: false,
    vote_average: 7.663,
    vote_count: 3911,
  },
  {
    adult: false,
    backdrop_path: '/pA4sNvcohTNPx3AhEEeIu8gSt7h.jpg',
    genre_ids: [16, 35, 10751, 14, 10749, 12],
    id: 976573,
    original_language: 'en',
    original_title: 'Elemental',
    overview:
      'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
    popularity: 264.051,
    poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
    release_date: '2023-06-14',
    title: 'Elemental',
    video: false,
    vote_average: 7.663,
    vote_count: 3911,
  },
  {
    adult: false,
    backdrop_path: '/iqqMJwvPlovftBfdHVrpP2B1IxE.jpg',
    genre_ids: [28, 80, 53, 18],
    id: 551115,
    original_language: 'nl',
    original_title: 'Penoza: The Final Chapter',
    overview:
      'The Black Widow is not dead ... Drug Queen Carmen van Walraven is hiding in Canada and leads an anonymous life there. One evening a colleague is harassed and Carmen helps her. In self-defense, she kills the perpetrator, is arrested and extradited to the Netherlands. While her children are in shock that their mother is still alive, there are also some people who still have to settle something with Carmen. Everyone is again dragged into an emotional rollercoaster. Carmen will now have deal with her past to save her family.',
    popularity: 350.27,
    poster_path: '/ba1NlageLgbxOPLXjX0qX7HDBTc.jpg',
    release_date: '2019-11-28',
    title: 'Penoza: The Final Chapter',
    video: false,
    vote_average: 7.172,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: '/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg',
    genre_ids: [18, 878, 28],
    id: 695721,
    original_language: 'en',
    original_title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    overview:
      '64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.',
    popularity: 261.292,
    poster_path: '/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg',
    release_date: '2023-11-15',
    title: 'The Hunger Games: The Ballad of Songbirds & Snakes',
    video: false,
    vote_average: 7.182,
    vote_count: 2060,
  },
  {
    adult: false,
    backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
    genre_ids: [12, 28, 878],
    id: 299536,
    original_language: 'en',
    original_title: 'Avengers: Infinity War',
    overview:
      'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
    popularity: 246.341,
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    release_date: '2018-04-25',
    title: 'Avengers: Infinity War',
    video: false,
    vote_average: 8.248,
    vote_count: 28727,
  },
  {
    adult: false,
    backdrop_path: '/kSdIVZu7Cv60o9hTbKBzcTrbMX8.jpg',
    genre_ids: [28, 53],
    id: 984249,
    original_language: 'en',
    original_title: 'Ruthless',
    overview:
      'A high school coach, whose teenage daughter was murdered, takes matters into his own hands by going after the men who kidnap his students for their sex trafficking operation.',
    popularity: 314.94,
    poster_path: '/4ndp1pnHWRuiZLNpFJvO4Kh6Tav.jpg',
    release_date: '2023-12-14',
    title: 'Ruthless',
    video: false,
    vote_average: 6.5,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: '/wmFAIzObxg4Lm5dSmpE0USQpLDQ.jpg',
    genre_ids: [16, 10751],
    id: 645992,
    original_language: 'no',
    original_title: 'Folk og røvere i Kardemomme by',
    overview:
      'The three thieves Kasper, Jesper and Jonathan lives together with their always hungry lion in the little town of Kardemomme town, the home to a fair but kind police officer, and the strict Aunt Sofie.',
    popularity: 263.254,
    poster_path: '/trEe8yRZvMvQQD61tBrCAD6sqaB.jpg',
    release_date: '2022-12-25',
    title: 'Three Robbers and a Lion',
    video: false,
    vote_average: 6.5,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
    genre_ids: [35, 12],
    id: 346698,
    original_language: 'en',
    original_title: 'Barbie',
    overview:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    popularity: 259.717,
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    release_date: '2023-07-19',
    title: 'Barbie',
    video: false,
    vote_average: 7.089,
    vote_count: 7949,
  },
  {
    adult: false,
    backdrop_path: '/eHMh7kChaNeD4VTdMCXLJbRTzcI.jpg',
    genre_ids: [18, 36, 10752],
    id: 753342,
    original_language: 'en',
    original_title: 'Napoleon',
    overview:
      'An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.',
    popularity: 265.544,
    poster_path: '/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg',
    release_date: '2023-11-22',
    title: 'Napoleon',
    video: false,
    vote_average: 6.485,
    vote_count: 1965,
  },
  {
    adult: false,
    backdrop_path: '/aINel9503ompOlGKn4sIVMg09Un.jpg',
    genre_ids: [9648, 27, 53],
    id: 838209,
    original_language: 'ko',
    original_title: '파묘',
    overview:
      "After tracing the origin of a disturbing supernatural affliction to a wealthy family's ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.",
    popularity: 269.266,
    poster_path: '/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg',
    release_date: '2024-02-22',
    title: 'Exhuma',
    video: false,
    vote_average: 7.8,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: 'en',
    original_title: 'Spider-Man: No Way Home',
    overview:
      'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    popularity: 254.21,
    poster_path: '/5weKu49pzJCt06OPpjvT80efnQj.jpg',
    release_date: '2021-12-15',
    title: 'Spider-Man: No Way Home',
    video: false,
    vote_average: 7.97,
    vote_count: 19245,
  },
  {
    adult: false,
    backdrop_path: '/6SLyu9ygASsrOqkCpjAwtyG9PWW.jpg',
    genre_ids: [10751, 878, 28, 35],
    id: 1094556,
    original_language: 'en',
    original_title: 'The Thundermans Return',
    overview:
      "Twins Phoebe and Max are enjoying their superhero lifestyle, but when one 'save' goes awry, the Thundermans are sent back to Hiddenville. While Hank and Barb enjoy their return, and Billy and Nora look forward to a normal high school life, Max and Phoebe are determined to regain their superhero status.",
    popularity: 251.702,
    poster_path: '/2J5eeroLDY0d45mVjpuGhcLZs3W.jpg',
    release_date: '2024-03-07',
    title: 'The Thundermans Return',
    video: false,
    vote_average: 7.668,
    vote_count: 95,
  },
  {
    adult: false,
    backdrop_path: '/unvtbkgxh47BewQ8pENvdOdme0r.jpg',
    genre_ids: [28],
    id: 1212073,
    original_language: 'de',
    original_title: '60 Minuten',
    overview:
      'Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.',
    popularity: 252.056,
    poster_path: '/jojfbnIHGsRpodIood3OQoqA45Y.jpg',
    release_date: '2024-01-19',
    title: 'Sixty Minutes',
    video: false,
    vote_average: 6.793,
    vote_count: 458,
  },
  {
    adult: false,
    backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    genre_ids: [16, 28, 12, 878],
    id: 569094,
    original_language: 'en',
    original_title: 'Spider-Man: Across the Spider-Verse',
    overview:
      'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
    popularity: 245.533,
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    release_date: '2023-05-31',
    title: 'Spider-Man: Across the Spider-Verse',
    video: false,
    vote_average: 8.377,
    vote_count: 6099,
  },
  {
    adult: false,
    backdrop_path: '/xg4BiG7tV6nl8VG9nsSdh3jype.jpg',
    genre_ids: [12, 28],
    id: 893334,
    original_language: 'en',
    original_title: 'The Adventures of Maid Marian',
    overview:
      'Everyone knows the stories of Robin Hood and Maid Marian, but this the story of what happens next. Out of the shadows, a legend returns to save her people from the tyranny of the disgraced Sheriff of Nottingham. Robin Hood remains at war and Marian must put her own combat skills to the test, creating a new tale that will be heralded throughout the ages.',
    popularity: 326.438,
    poster_path: '/oPXzCV01ysDmnmpJOkiVqaZQ5QR.jpg',
    release_date: '2022-05-09',
    title: 'The Adventures of Maid Marian',
    video: false,
    vote_average: 4.0,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
    genre_ids: [16, 12, 14, 35, 28, 10751],
    id: 315162,
    original_language: 'en',
    original_title: 'Puss in Boots: The Last Wish',
    overview:
      'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
    popularity: 240.416,
    poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
    release_date: '2022-12-07',
    title: 'Puss in Boots: The Last Wish',
    video: false,
    vote_average: 8.242,
    vote_count: 7167,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [16, 14],
    id: 59300,
    original_language: 'ja',
    original_title: 'デンゼルを中心としたオリジナルアニメ',
    overview:
      "It's been four years since Meteor fell on Midgar. Denzel meets Reeve at an outskirts coffee shop about joining the World Regenesis Organization. Upon the request Denzel tells Reeve about what his life was like prior to the Meteor incident.",
    popularity: 266.448,
    poster_path: '/jn0qp1t7mExBze9qzy4pryFCbpm.jpg',
    release_date: '2009-04-16',
    title: 'Final Fantasy VII: On the Way to a Smile - Episode Denzel',
    video: false,
    vote_average: 5.533,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: '/xPTefQ4CZpWapxiEsAZsxtidS49.jpg',
    genre_ids: [10751, 878],
    id: 682075,
    original_language: 'en',
    original_title: 'The Adventure of A.R.I.: My Robot Friend',
    overview:
      'A teenager summons the courage to help a friendly robot known as A.R.I. kidnapped by a ruthless lab director working for a powerful corporation seeking to turn him into a dangerous weapon in order to rule the world.',
    popularity: 257.366,
    poster_path: '/txcjXiyhBvsSFyZtgCHWW7CyIeN.jpg',
    release_date: '2022-01-13',
    title: 'The Adventure of A.R.I.: My Robot Friend',
    video: false,
    vote_average: 7.278,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/d1RHScaZc7I8j0lDke1c4AxI435.jpg',
    genre_ids: [28, 12, 16, 10751, 35],
    id: 9502,
    original_language: 'en',
    original_title: 'Kung Fu Panda',
    overview:
      'When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.',
    popularity: 241.765,
    poster_path: '/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg',
    release_date: '2008-06-04',
    title: 'Kung Fu Panda',
    video: false,
    vote_average: 7.275,
    vote_count: 11062,
  },
  {
    adult: false,
    backdrop_path: '/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg',
    genre_ids: [16, 10751, 12, 18, 35],
    id: 150540,
    original_language: 'en',
    original_title: 'Inside Out',
    overview:
      'From an adventurous balloon ride above the clouds to a monster-filled metropolis, Academy Award®-winning director Pete Docter (“Monsters, Inc.,” “Up”) has taken audiences to unique and imaginative places. In Disney and Pixar’s original movie “ Inside Out,” he will take us to the most extraordinary location of all—inside the mind.',
    popularity: 216.994,
    poster_path: '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
    release_date: '2015-06-09',
    title: 'Inside Out',
    video: false,
    vote_average: 7.917,
    vote_count: 20196,
  },
  {
    adult: false,
    backdrop_path: '/sfKIRZ7jjOYZXMlg1waEkFrZrNN.jpg',
    genre_ids: [16, 35, 10751],
    id: 1216512,
    original_language: 'en',
    original_title: 'The Casagrandes Movie',
    overview:
      "On a birthday trip to Mexico, 12-year-old Ronnie Anne accidentally frees a demigod trapped in a mountain and needs her family's help to set things right.",
    popularity: 239.095,
    poster_path: '/1ZHetsKD44xB63ZjTjqryC0CtoL.jpg',
    release_date: '2024-03-22',
    title: 'The Casagrandes Movie',
    video: false,
    vote_average: 7.675,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: '/sfKIRZ7jjOYZXMlg1waEkFrZrNN.jpg',
    genre_ids: [16, 35, 10751],
    id: 1216512,
    original_language: 'en',
    original_title: 'The Casagrandes Movie',
    overview:
      "On a birthday trip to Mexico, 12-year-old Ronnie Anne accidentally frees a demigod trapped in a mountain and needs her family's help to set things right.",
    popularity: 239.095,
    poster_path: '/1ZHetsKD44xB63ZjTjqryC0CtoL.jpg',
    release_date: '2024-03-22',
    title: 'The Casagrandes Movie',
    video: false,
    vote_average: 7.786,
    vote_count: 21,
  },
  {
    adult: false,
    backdrop_path: '/y9Dr6yCVYRmjKuDjOjNyWxVuGjp.jpg',
    genre_ids: [80, 28],
    id: 370464,
    original_language: 'en',
    original_title: 'The Masked Saint',
    overview:
      'The journey of a professional wrestler who becomes a small town pastor and moonlights as a masked vigilante fighting injustice. While facing crises at home and at the church, the Pastor must evade the police and somehow reconcile his violent secret identity with his calling as a pastor.',
    popularity: 269.769,
    poster_path: '/zlT1Tc9hA1Ntye5hr7Gxos9U6U9.jpg',
    release_date: '2016-01-08',
    title: 'The Masked Saint',
    video: false,
    vote_average: 4.7,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/jkBFGhuJKLH8VurXqVKQ2mxvVYC.jpg',
    genre_ids: [37],
    id: 1079394,
    original_language: 'en',
    original_title: 'The Five',
    overview:
      'A scorned woman enlists the help of five strangers to execute a bank robbery. Tensions rise as the men anxiously await her arrival with the money, leaving the crew to wonder if they have been betrayed.',
    popularity: 265.181,
    poster_path: '/xckDPGprPVDpuzhSyo9E7SZJ2wa.jpg',
    release_date: '2023-01-07',
    title: 'The Five',
    video: false,
    vote_average: 6.182,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: '/1ZSKH5GGFlM8M32K34GMdaNS2Ew.jpg',
    genre_ids: [10402, 36, 18],
    id: 802219,
    original_language: 'en',
    original_title: 'Bob Marley: One Love',
    overview:
      'Jamaican singer-songwriter Bob Marley overcomes adversity to become the most famous reggae musician in the world.',
    popularity: 240.89,
    poster_path: '/mKWalirPreEdCKDJjc5TKeOP2xi.jpg',
    release_date: '2024-02-14',
    title: 'Bob Marley: One Love',
    video: false,
    vote_average: 7.0,
    vote_count: 454,
  },
  {
    adult: false,
    backdrop_path: '/r9oTasGQofvkQY5vlUXglneF64Z.jpg',
    genre_ids: [28, 35],
    id: 1029575,
    original_language: 'en',
    original_title: 'The Family Plan',
    overview:
      "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
    popularity: 270.676,
    poster_path: '/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg',
    release_date: '2023-12-14',
    title: 'The Family Plan',
    video: false,
    vote_average: 7.324,
    vote_count: 1105,
  },
  {
    adult: false,
    backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
    genre_ids: [28, 12, 878],
    id: 298618,
    original_language: 'en',
    original_title: 'The Flash',
    overview:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    popularity: 238.796,
    poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
    release_date: '2023-06-13',
    title: 'The Flash',
    video: false,
    vote_average: 6.755,
    vote_count: 3793,
  },
  {
    adult: false,
    backdrop_path: '/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg',
    genre_ids: [16, 35, 18, 10751],
    id: 838240,
    original_language: 'es',
    original_title: 'Robot Dreams',
    overview:
      "Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of '80s NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
    popularity: 222.671,
    poster_path: '/rUPJfjfNEbANXQrmCQfurOppqrA.jpg',
    release_date: '2023-10-20',
    title: 'Robot Dreams',
    video: false,
    vote_average: 7.841,
    vote_count: 227,
  },
  {
    adult: false,
    backdrop_path: '/pWsD91G2R1Da3AKM3ymr3UoIfRb.jpg',
    genre_ids: [878, 28],
    id: 933131,
    original_language: 'ko',
    original_title: '황야',
    overview:
      'After a deadly earthquake turns Seoul into a lawless badland, a fearless huntsman springs into action to rescue a teenager abducted by a mad doctor.',
    popularity: 238.557,
    poster_path: '/sdI9ufheNPAKnWLl2hnsZKVk0EG.jpg',
    release_date: '2024-01-25',
    title: 'Badland Hunters',
    video: false,
    vote_average: 6.768,
    vote_count: 576,
  },
  {
    adult: false,
    backdrop_path: '/7I6VUdPj6tQECNHdviJkUHD2u89.jpg',
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    popularity: 232.773,
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    release_date: '2023-03-22',
    title: 'John Wick: Chapter 4',
    video: false,
    vote_average: 7.743,
    vote_count: 5795,
  },
  {
    adult: false,
    backdrop_path: '/jks6QgJjsaDC5iT6bxLsSS0eo6L.jpg',
    genre_ids: [28, 12, 14],
    id: 293167,
    original_language: 'en',
    original_title: 'Kong: Skull Island',
    overview:
      'Explore the mysterious and dangerous home of the king of the apes as a team of explorers ventures deep inside the treacherous, primordial island.',
    popularity: 251.042,
    poster_path: '/r2517Vz9EhDhj88qwbDVj8DCRZN.jpg',
    release_date: '2017-03-08',
    title: 'Kong: Skull Island',
    video: false,
    vote_average: 6.53,
    vote_count: 10067,
  },
  {
    adult: false,
    backdrop_path: '/zgQQF04u3OgNBJqClRNby1FPz9s.jpg',
    genre_ids: [16, 10751, 28, 878, 35, 18, 12],
    id: 893723,
    original_language: 'en',
    original_title: 'PAW Patrol: The Mighty Movie',
    overview:
      'A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.',
    popularity: 211.366,
    poster_path: '/aTvePCU7exLepwg5hWySjwxojQK.jpg',
    release_date: '2023-09-21',
    title: 'PAW Patrol: The Mighty Movie',
    video: false,
    vote_average: 7.109,
    vote_count: 373,
  },
  {
    adult: false,
    backdrop_path: '/xStFwzqBWDRyUz3BldisuUY7kjW.jpg',
    genre_ids: [14, 12, 10770],
    id: 885303,
    original_language: 'it',
    original_title: 'I viaggiatori',
    overview:
      "Time jump to 1939 with teenager Max and his friends as they try to navigate Mussolini's Rome and find Max's missing brother.",
    popularity: 279.805,
    poster_path: '/38N7GRJLu7IWyEdil96YobJ5LWM.jpg',
    release_date: '2022-11-21',
    title: 'The Voyagers',
    video: false,
    vote_average: 5.5,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: '/14xx5Tf58mD8FRJ1B3BspiLiRxz.jpg',
    genre_ids: [12, 18, 28],
    id: 254,
    original_language: 'en',
    original_title: 'King Kong',
    overview:
      'In 1933 New York, an overly ambitious movie producer coerces his cast and hired ship crew to travel to mysterious Skull Island, where they encounter Kong, a giant ape who is immediately smitten with the leading lady.',
    popularity: 225.588,
    poster_path: '/4fNOp3itFBw7L28kAHxwRPqyZ2K.jpg',
    release_date: '2005-12-12',
    title: 'King Kong',
    video: false,
    vote_average: 6.88,
    vote_count: 7573,
  },
  {
    adult: false,
    backdrop_path: '/tg1cQrXw7G5kbapdAoqc0oHtYdN.jpg',
    genre_ids: [27, 878],
    id: 981347,
    original_language: 'en',
    original_title: 'The Loch Ness Horror',
    overview:
      'A vanished submarine prompts a rescue operation that leads to the Loch Ness monster. Having escaped the Loch, the creature unleashes decades of pent-up aggression on those it encounters.',
    popularity: 241.591,
    poster_path: '/fFdG5U2PzhRrHRpbbORQrcAMn8D.jpg',
    release_date: '2023-11-07',
    title: 'The Loch Ness Horror',
    video: false,
    vote_average: 6.367,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: '/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg',
    genre_ids: [28, 878, 27],
    id: 615656,
    original_language: 'en',
    original_title: 'Meg 2: The Trench',
    overview:
      'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
    popularity: 248.103,
    poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
    release_date: '2023-08-02',
    title: 'Meg 2: The Trench',
    video: false,
    vote_average: 6.589,
    vote_count: 3052,
  },
  {
    adult: false,
    backdrop_path: '/mmpnUZebJhFXewEUuP7OGM4GuNF.jpg',
    genre_ids: [878, 12, 18],
    id: 636706,
    original_language: 'en',
    original_title: 'Spaceman',
    overview:
      'During a research mission, an astronaut discovers that his marriage is in trouble. Luckily, he has the help of a mysterious creature hidden in his ship.',
    popularity: 156.618,
    poster_path: '/5hnFFOWEchErNVr0wMLWFEob3q1.jpg',
    release_date: '2024-02-23',
    title: 'Spaceman',
    video: false,
    vote_average: 6.845,
    vote_count: 511,
  },
  {
    adult: false,
    backdrop_path: '/jrSjFod386IYl29ALnbtWbysLhj.jpg',
    genre_ids: [28, 53],
    id: 575264,
    original_language: 'en',
    original_title: 'Mission: Impossible - Dead Reckoning Part One',
    overview:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
    popularity: 201.881,
    poster_path: '/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    release_date: '2023-07-08',
    title: 'Mission: Impossible - Dead Reckoning Part One',
    video: false,
    vote_average: 7.6,
    vote_count: 3309,
  },
  {
    adult: false,
    backdrop_path: '/1tDMeyxEMa2zNMWL8BXvXydKxTX.jpg',
    genre_ids: [18],
    id: 857655,
    original_language: 'en',
    original_title: 'The Beautiful Game',
    overview:
      'Advocates to end homelessness, organize an annual tournament for Homeless people to compete in a series of football matches known as The Homeless World Cup.',
    popularity: 159.433,
    poster_path: '/3Laz0p3Qg47vI2XIalpL2SlNUDI.jpg',
    release_date: '2024-03-22',
    title: 'The Beautiful Game',
    video: false,
    vote_average: 6.595,
    vote_count: 58,
  },
  {
    adult: false,
    backdrop_path: '/47SVqaO02doJ06tOmrjiWDkwU3T.jpg',
    genre_ids: [28, 53],
    id: 927107,
    original_language: 'en',
    original_title: 'The Bricklayer',
    overview:
      'Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant – and rebellious – operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.',
    popularity: 184.795,
    poster_path: '/36pYugctLa70NmwMEgXTR1G31Kq.jpg',
    release_date: '2023-12-14',
    title: 'The Bricklayer',
    video: false,
    vote_average: 5.961,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: '/auXrHU6O17n9Tz11SHReoorjrU6.jpg',
    genre_ids: [16, 35, 10751],
    id: 1075794,
    original_language: 'en',
    original_title: 'Leo',
    overview:
      'Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.',
    popularity: 210.398,
    poster_path: '/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg',
    release_date: '2023-11-17',
    title: 'Leo',
    video: false,
    vote_average: 7.495,
    vote_count: 1027,
  },
  {
    adult: false,
    backdrop_path: '/shS6buEDnEDoHTdLbGzCoDIZ9ur.jpg',
    genre_ids: [27],
    id: 840889,
    original_language: 'en',
    original_title: 'Stopmotion',
    overview:
      'Ella Blake, a stop-motion animator struggling to control her demons after the loss of her overbearing mother, embarks upon the creation of a film that becomes the battleground for her sanity. As Ella’s mind starts to fracture, the characters in her project take on a life of their own.',
    popularity: 230.019,
    poster_path: '/kWzWZEctPcZ0dATbtcYy6lIJgGj.jpg',
    release_date: '2024-02-22',
    title: 'Stopmotion',
    video: false,
    vote_average: 6.745,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: '/zMtBbNhROxPf0urHSBoZUnqJEwT.jpg',
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: 'en',
    original_title: 'Trolls Band Together',
    overview:
      "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 198.301,
    poster_path: '/bkpPTZUdq31UGDovmszsg2CchiI.jpg',
    release_date: '2023-10-12',
    title: 'Trolls Band Together',
    video: false,
    vote_average: 7.321,
    vote_count: 728,
  },
  {
    adult: false,
    backdrop_path: '/uT5G4fA7jKxlJNfwYPMm353f5AI.jpg',
    genre_ids: [28, 12, 16, 35, 10751],
    id: 140300,
    original_language: 'en',
    original_title: 'Kung Fu Panda 3',
    overview:
      'While Po and his father are visiting a secret panda village, an evil spirit threatens all of China, forcing Po to form a ragtag army to fight back.',
    popularity: 178.898,
    poster_path: '/oajNi4Su39WAByHI6EONu8G8HYn.jpg',
    release_date: '2016-01-23',
    title: 'Kung Fu Panda 3',
    video: false,
    vote_average: 6.902,
    vote_count: 5672,
  },
  {
    adult: false,
    backdrop_path: '/xi2pblvQtCnh26SeOYzx1YX3DLT.jpg',
    genre_ids: [80, 28, 53],
    id: 1227816,
    original_language: 'en',
    original_title: 'Red Right Hand',
    overview:
      "Cash is trying to live a quiet, honest life in a small Appalachian town. When a vicious crime boss forces him back into her services, he soon learns he's capable of anything -- even killing -- to protect his family and his home.",
    popularity: 258.972,
    poster_path: '/vfEG79SQIg3p6B8rBLVeIo2BBhb.jpg',
    release_date: '2024-02-22',
    title: 'Red Right Hand',
    video: false,
    vote_average: 7.4,
    vote_count: 78,
  },
  {
    adult: false,
    backdrop_path: '/l6w0qCPRJ2ANAv9pEBMk8WBN1vD.jpg',
    genre_ids: [28, 35],
    id: 1217409,
    original_language: 'es',
    original_title: 'Jaque Mate',
    overview:
      'Duque, an international secret agent who retired years ago after a traumatic event, is forced to return to action when a commando operative kidnaps his niece and forces him to steal a precious scientific formula as part of the ransom.',
    popularity: 233.036,
    poster_path: '/o960Qx10rRRA4t44DsjeiYB3Dmh.jpg',
    release_date: '2024-01-25',
    title: 'Jaque Mate',
    video: false,
    vote_average: 4.955,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: '/mOQV573Tr0WxI2VVOLKwtfaRGZH.jpg',
    genre_ids: [10749, 35, 12],
    id: 949429,
    original_language: 'th',
    original_title: 'ผจญภัยล่าขุมทรัพย์หมื่นลี้',
    overview:
      'Joy, a secretary at a large multinational company, has an online shopping problem, likes to read adventure novels and watch travel and adventure shows. She daydreams about living a life of adventure.',
    popularity: 238.782,
    poster_path: '/z3SeS4wjKQ3TjHSvRidovGJbHYb.jpg',
    release_date: '2023-12-22',
    title: 'The Adventures',
    video: false,
    vote_average: 6.389,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: '/eTlcNXGv32zkVI7ZDHhfeaKHXKQ.jpg',
    genre_ids: [28, 9648, 878, 53],
    id: 198663,
    original_language: 'en',
    original_title: 'The Maze Runner',
    overview:
      "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
    popularity: 209.981,
    poster_path: '/ode14q7WtDugFDp78fo9lCsmay9.jpg',
    release_date: '2014-09-10',
    title: 'The Maze Runner',
    video: false,
    vote_average: 7.177,
    vote_count: 16398,
  },
  {
    adult: false,
    backdrop_path: '/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg',
    genre_ids: [16, 10751, 35, 14],
    id: 1139829,
    original_language: 'en',
    original_title: 'Orion and the Dark',
    overview:
      'A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.',
    popularity: 191.678,
    poster_path: '/oT53tpbp12PfJ0ifCs71Viue8R8.jpg',
    release_date: '2024-02-01',
    title: 'Orion and the Dark',
    video: false,
    vote_average: 6.647,
    vote_count: 377,
  },
  {
    adult: false,
    backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: 'en',
    original_title: 'Avatar',
    overview:
      'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
    popularity: 155.053,
    poster_path: '/kyeqWdyUXW608qlYkRqosgbbJyK.jpg',
    release_date: '2009-12-15',
    title: 'Avatar',
    video: false,
    vote_average: 7.58,
    vote_count: 30706,
  },
  {
    adult: false,
    backdrop_path: '/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg',
    genre_ids: [28, 878, 53],
    id: 799155,
    original_language: 'hi',
    original_title: 'Attack',
    overview:
      'With the Parliament under siege, India’s first super soldier Arjun Shergill is tasked to get hold of the terrorists in the nick of time, save the Prime Minister from their clutches and stop a dirty bomb from exploding and destroying Delhi. Will Arjun succeed in his mission?',
    popularity: 224.864,
    poster_path: '/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg',
    release_date: '2022-04-01',
    title: 'Attack',
    video: false,
    vote_average: 6.65,
    vote_count: 180,
  },
  {
    adult: false,
    backdrop_path: '/xUL7qsAKisRg5iBEokW98OndJDf.jpg',
    genre_ids: [12, 28, 35, 10749],
    id: 14324,
    original_language: 'en',
    original_title: 'Virgin Territory',
    overview:
      'The film is set in Tuscany during the Black Death. As in the Decameron, ten young Florentines take refuge from the plague. But instead of telling stories, they have lusty adventures, bawdy exchanges, romance and swordplay. There are randy nuns, Saracen pirates, and a sexy cow.',
    popularity: 109.015,
    poster_path: '/bPdE1CbdP8Bf1NMg9PF4QkPR9oZ.jpg',
    release_date: '2007-12-17',
    title: 'Virgin Territory',
    video: false,
    vote_average: 4.7,
    vote_count: 297,
  },
  {
    adult: false,
    backdrop_path: '/hziiv14OpD73u9gAak4XDDfBKa2.jpg',
    genre_ids: [12, 14],
    id: 671,
    original_language: 'en',
    original_title: "Harry Potter and the Philosopher's Stone",
    overview:
      "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
    popularity: 183.708,
    poster_path: '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    release_date: '2001-11-16',
    title: "Harry Potter and the Philosopher's Stone",
    video: false,
    vote_average: 7.914,
    vote_count: 26407,
  },
  {
    adult: false,
    backdrop_path: '/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg',
    genre_ids: [28, 12, 53],
    id: 299054,
    original_language: 'en',
    original_title: 'Expend4bles',
    overview:
      'Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.',
    popularity: 206.948,
    poster_path: '/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg',
    release_date: '2023-09-15',
    title: 'Expend4bles',
    video: false,
    vote_average: 6.336,
    vote_count: 1262,
  },
  {
    adult: false,
    backdrop_path: '/elH2ZWRHOKpjUNHROvpTCZIvuO7.jpg',
    genre_ids: [27, 53],
    id: 983526,
    original_language: 'no',
    original_title: 'Leave',
    overview:
      'A young woman tries to find her origins after having been abandoned as an infant at a cemetery wrapped in a cloth with satanic symbols, but as she gets closer to answers a malevolent spirit is telling her to leave.',
    popularity: 225.933,
    poster_path: '/aiw8k5wXSCkueUD7eavmnNtaQFO.jpg',
    release_date: '2022-10-28',
    title: 'Leave',
    video: false,
    vote_average: 6.046,
    vote_count: 54,
  },
  {
    adult: false,
    backdrop_path: '/giLoSoPXYTB4vtB5jOiRhhltL8H.jpg',
    genre_ids: [10749, 35],
    id: 1257130,
    original_language: 'pl',
    original_title: 'Nic na siłę',
    overview:
      "After being tricked into dropping everything to save her grandmother's farm, big-city chef Oliwia falls for a handsome farmer who's hiding a secret.",
    popularity: 212.789,
    poster_path: '/mlGjb0Cku6EVYNg1VM0cddwIgkX.jpg',
    release_date: '2024-03-27',
    title: 'No Pressure',
    video: false,
    vote_average: 4.9,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/G56AzECyTDp63sE7CbJ6AEBKhF.jpg',
    genre_ids: [37, 28],
    id: 851925,
    original_language: 'en',
    original_title: 'Death Alley',
    overview:
      'In 1892, the Dalton Gang set out to become the most famous outlaws in America. That dream would become a nightmare.',
    popularity: 228.377,
    poster_path: '/iIKYK9mdapWlJ21YNRGB57WKErK.jpg',
    release_date: '2021-03-11',
    title: 'Death Alley',
    video: false,
    vote_average: 5.391,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: '/q3j4OQFFDKM6fdQt9gE56kfDBNG.jpg',
    genre_ids: [16, 878, 28, 12],
    id: 536115,
    original_language: 'ja',
    original_title: 'GODZILLA 星を喰う者',
    overview:
      'With no means for defeating Godzilla Earth, mankind watches as King Ghidorah, clad in a golden light, descends on the planet. The heavens and earth shake once again as the war moves to a higher dimension.',
    popularity: 173.408,
    poster_path: '/fOA44BITFth0u4hMSOUgpK0kM6t.jpg',
    release_date: '2018-11-09',
    title: 'Godzilla: The Planet Eater',
    video: false,
    vote_average: 6.411,
    vote_count: 305,
  },
  {
    adult: false,
    backdrop_path: '/9JNsAIFMu4o37AgnU1JVtR6AWsK.jpg',
    genre_ids: [10749, 28, 18],
    id: 1248795,
    original_language: 'tr',
    original_title: 'Romantik Hırsız',
    overview:
      'After learning that the art thief she has been chasing is her ex-lover, an officer working for Interpol concocts a plan to catch him red-handed.',
    popularity: 201.424,
    poster_path: '/niVtvS9Kf8G1VDPSqurqHkaSSwm.jpg',
    release_date: '2024-03-14',
    title: 'Art of Love',
    video: false,
    vote_average: 6.73,
    vote_count: 89,
  },
  {
    adult: false,
    backdrop_path: '/dvpzY91fvfcWSYgb0Xlan2NNLLU.jpg',
    genre_ids: [28, 53],
    id: 560016,
    original_language: 'en',
    original_title: 'Monkey Man',
    overview:
      'Kid, an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.',
    popularity: 158.879,
    poster_path: '/b4fn3VIdVTT3SX0rFMNFbl5xuvg.jpg',
    release_date: '2024-04-03',
    title: 'Monkey Man',
    video: false,
    vote_average: 7.7,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: '/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
    genre_ids: [80, 9648, 53],
    id: 414906,
    original_language: 'en',
    original_title: 'The Batman',
    overview:
      'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    popularity: 234.124,
    poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    release_date: '2022-03-01',
    title: 'The Batman',
    video: false,
    vote_average: 7.683,
    vote_count: 9417,
  },

  // Add more movie objects as needed
];

module.exports = {
  users,
  customers,
  invoices,
  revenue,
  movies,
};
